### ISSUE TITLE
Try GH Actions

### ISSUE THREAD

**Issue by case** [zonedb/zonedb#783]
#### Todo

- [x] get building working
- [x] get tests running
- [ ] reporting: confirm we don't need `store_test_results` and `store_artifacts`
- [ ] confirm what `deploy` does, in `jobs: build`
- [ ] look into breaking up build + test into separate steps, and persisting whatever they need via a working directory
- [ ] get `update` working, with changes committed and pushed 
- [ ] cron schedule for `make update`

#### Related

- [helpful info about Actions + Go](https://github.com/mvdan/github-actions-golang)

**Comment by case** [comment]
This is done.
